covid19-kitakyushu/covid19

components/SideNavigation.vue
- close #9
- 北九州市様の要望を確認し、facebookとLINEアイコンのリンク先を公式ページに変更した
=> SNSリンクを北九州市公式に変更

.github/workflows/staging.yml
- close #0
- close #0
- #0
- #0
- stagingへのdeployActionを北九州用に修正
=> fix deploy for kitakyushu

pages/index.vue
- close #21 
- リンク先の変更
- ボタン削除
=> リンク変更、ボタン削除

components/DevelopmentModeMark.vue
- close #0
- close #0
- #0
- #0
- staging環境で表示される公開サイトへのリンクを北九州のものに変更
=> 公開サイトの宛先を北九州のURLに変更

assets/locales/ja.json, layouts/default.vue
- close #13
- OGP.pngだけを変えていたが、urlやdescriptionも変更
- local環境では確認ができない。
=> test OGP change

components/SideNavigation.vue
- close #20
- お問い合わせ先のリンク変更
- その他のサイドバーリンクは変更なしで確認
=> お問い合わせ先のリンク変更

nuxt.config.ts
- close #47
- #47
- nuxt.config.ts にOGP定義を明確に書いた
=> nuxt.config.tsのOGP定義を変更

components/SideNavigation.vue
- close #63
- サイドナビゲーション内のFAIS様の位置を修正
- Code for Kitakyushu のリンク切れ修正
=> FAIS様を協力に移動。Code4KitaQのリンク切れ修正

data/news.json
- close #65 
- close #0
- #0
- #0
- news.jsonを仕様変更後に修正
- 更新されないようdeploy/resourcesのnews.json削除、actions修正
=> news.json修正

components/cards/ConfirmedCasesNumberCard.vue
- close #77
- オープンデータのリンク先をテスト数から陽性患者属性に修正
=> 陽性患者数のオープンデータリンクを修正

components/DataView.vue
- close #59
- close #0
- #0
- #0
- 更新日時のリンク機能を削除
- xxx
=> 更新日時link削除

components/SideNavigation.vue
- close #81
- サイドナビゲーションのリンク先をfacebookのページに変更
=> Code for Kitakyushuのリンク先変更

components/cards/ConfirmedCasesAttributesCard.vue, components/cards/ConfirmedCasesNumberCard.vue, utils/formatGraphForPatients.ts
-陽性患者数の実績値表示日時を修正
- #0
- #0
- xxxxxx
- xxx
=> fix Actual Value

pages/index.vue
- ページ上部の最終更新日時をデータ更新のたびに変わるよう修正
- #0
- #0
- xxxxxx
- xxx
=> fix lastUpdate

components/SideNavigation.vue
- close #146
- #0
- #0
- youtubeのリンク先変更
=> youtubeリンク変更

nuxt.config.ts
- 陽性患者カードで、「テーブルを表示」が表示されない
- development では再現せず、Staging と Master でのみ再現する
- treeShake はdevelopment と production で CSS の反映が変化することを避けるための設定で
　東京サイトでも設定しているため、まず Staging 環境で確認したい
=> Test treeShake

assets/variables.scss, components/DataView.vue
- close #189
- 東京版の変更をマージ
- vuetifyのexpansion panelを利用
=> Add Expansion Panel

components/cards/ConfirmedCasesNumberCard.vue
- close #189
- 効果は不明だが、無駄な<template>を削除
Stagingで確認
=> 不要なテンプレートタグを削除

components/DataView.vue
- close #189
- DataView.vueの該当箇所を東京版からimport
=> DataView.vueのTSコードを東京版からインポート

.github/workflows/deploy.yml
- close #0
- close #0
- #0
- #0
- xxxxxx
- xxx
=> rm protection-bot

assets/variables.scss, components/ConfirmedCasesDetailsTable.vue, components/cards/ConfirmedCasesDetailsCard.vue, pages/index.vue, utils/formatConfirmedCases.ts
Reverts covid19-kitakyushu/covid19#255
=> Revert "検査陽性者の状況カードを追加"

components/DataView.vue, components/SideNavigation.vue, components/cards/ConfirmedCasesAttributesCard.vue, components/cards/InspectionBreakdownCard.vue, components/cards/TestedNumberCard.vue, layouts/default.vue, nuxt.config.ts, pages/cards/_card.vue, pages/index.vue
- close #364
- ErrorはshowOverlay のSNS共有機能削減で発生。不要コードを削除した
- i18nのWARNは、翻訳文字列の変換関数呼び出しを削除 (どこかに文字列登録しても良いが、多言語対応の予定がないため削除にした)
=> エラーとi18nのWARNを取る

components/InspectorBreakdownBarChart.vue, components/cards/InspectionBreakdownCard.vue, utils/colors.ts
- close #456 
- #0
- #0
-  検査実施件数内訳 に民間検査機関を追加
=> Add privaate test stack

assets/variables.scss, components/ConfirmedCasesDetailsTable.vue, components/cards/ConfirmedCasesDetailsCard.vue, pages/index.vue, utils/formatConfirmedCases.ts
- 新しく作られたオープンデータを使い、陽性患者の状況カードを追加
=> Add confirmed cases details

components/InspectorBreakdownBarChart.vue
検査件数内訳のテーブル件数誤り修正
- close #758
- #0
- #0
- 検査件数内訳のテーブル件数作成関数の修正
=> テーブルデータ生成部修正

components/InspectorBreakdownBarChart.vue
- close #0
- close #0
- #758
- #0
- 修正時のバグを再度修正
- xxx
=> fix off-by-one error
